version: '3.3'

services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./html:/usr/share/nginx/html
  db:
    image: postgres:10.14
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=pesho
    volumes:
    - sql_data:/var/lib/postgresql/data
  alpine:
    volumes:
      - ./entrypoint.sh:/home/script
    image: alpine:latest
    command: sh
    stdin_open: true
    tty: true 
    
volumes:
  sql_data:
